name: flutter_markdown_example
description: Demonstrates how to use the flutter_markdown_plus package.
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown_plus:
    path: ../

  markdown: ^7.3.0
  # BEGIN OPTIONAL DEMO DEPENDENCIES
  # flutter_markdown_plus_latex: ^1.0.4 # disabled
  # END OPTIONAL DEMO DEPENDENCIES


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  yaml: ^3.1.2 # For tool/configure_demos.dart

flutter:
  assets:
    - assets/

  fonts:
    - family: 'Roboto Mono'
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

  uses-material-design: true

dartfmt:
  line_length: 120
